"""
S216 exporter: BF closure certificate JSON → Lean file.

Generates a Lean module that:
  1. Hard-codes the dist table as `cert_m{m}_Q{Q}_S216_tbl`, optionally
     split into chunks for large tables.
  2. Defines `cert_m{m}_Q{Q}_S216_dist` as the partial function via List.find?.
  3. Defines three Bool checks (start, no_goal, closed) under the
     S216 optimistic relevance rule `d - (Q - j) < T`.
  4. Proves each via `native_decide`.

For tables larger than `CHUNK_THRESHOLD` rows, the table is split into
chunks of `CHUNK_SIZE` rows and the top-level `_tbl` is a `++` of them.
This bypasses Lean's quadratic-time elaboration of giant list literals.

Usage:
  python tools/cert_to_lean_s216.py <m> <Q> > CollatzLean4/CollatzLean4/Cert_m{m}_Q{Q}_S216.lean
"""
from __future__ import annotations
import sys
from s216_engine import S216Engine


CHUNK_THRESHOLD = 800
CHUNK_SIZE = 500


def _row(s) -> str:
    return f"(⟨{s['j']}, {s['c']}⟩, {s['dist']})"


def _emit_list_literal(states, indent="    ") -> list[str]:
    rows = []
    for i, s in enumerate(states):
        prefix = indent if i == 0 else "  , "
        rows.append(f"{prefix}{_row(s)}")
    return rows


def _emit_table(name: str, states) -> list[str]:
    """Emit either a single `def name : List ... := [..]` or a chunked
    sequence `name_chunk_i` + final `name := chunk_0 ++ chunk_1 ++ ...`."""
    out = []
    if len(states) <= CHUNK_THRESHOLD:
        out.append(f"def {name} : List (InvVertex × Int) :=")
        out.append(f"  [")
        out.extend(_emit_list_literal(states))
        out.append(f"  ]")
        out.append("")
        return out
    # Chunked emission.
    chunks = [states[i:i + CHUNK_SIZE] for i in range(0, len(states), CHUNK_SIZE)]
    for ci, chunk in enumerate(chunks):
        out.append(f"private def {name}_chunk_{ci} "
                   f": List (InvVertex × Int) :=")
        out.append(f"  [")
        out.extend(_emit_list_literal(chunk))
        out.append(f"  ]")
        out.append("")
    out.append(f"/-- Table assembled from {len(chunks)} chunks "
               f"of ≤{CHUNK_SIZE} rows each. -/")
    out.append(f"def {name} : List (InvVertex × Int) :=")
    concat = " ++ ".join(f"{name}_chunk_{ci}" for ci in range(len(chunks)))
    # Wrap concatenation across lines for readability.
    # For very many chunks (Q=10), keep on multiple lines.
    if len(chunks) <= 8:
        out.append(f"  {concat}")
    else:
        # Multi-line concatenation.
        per_line = 6
        groups = [concat.split(" ++ ")[i:i + per_line]
                  for i in range(0, len(chunks), per_line)]
        out.append(f"  {' ++ '.join(groups[0])}")
        for g in groups[1:]:
            out.append(f"  ++ {' ++ '.join(g)}")
    out.append("")
    return out


def emit_lean_s216(m: int, Q: int, max_states: int = 1_000_000) -> str:
    engine = S216Engine(m=m, Q=Q)
    cert = engine.search_or_certify_bf(max_states=max_states)

    if cert["status"] != "barrier_certificate":
        raise ValueError(
            f"No S216 certificate: status={cert['status']}, "
            f"states_seen={cert.get('states_seen', '?')}"
        )

    R = cert["R"]
    T = cert["threshold"]
    states = cert["states"]

    # Sanity self-verification before emitting:
    verify = engine.verify_bf_closure(cert)
    if not verify.get("ok"):
        raise ValueError(f"BF self-verification failed: {verify}")

    tbl_name = f"cert_m{m}_Q{Q}_S216_tbl"
    chunked = len(states) > CHUNK_THRESHOLD
    n_chunks = (len(states) + CHUNK_SIZE - 1) // CHUNK_SIZE if chunked else 1

    header = [
        f"/-",
        f"Auto-generated S216 BF closure certificate "
        f"(m={m}, Q={Q}, R={R}, T={T}).",
        f"",
        f"  - {cert['states_seen']} states explored, BF self-verified ✓",
        f"  - closure rule: d - (Q - j) < T  (S216 optimistic)",
        f"  - empirical conclusion: {cert['conclusion']}",
    ]
    if chunked:
        header.append(
            f"  - table emitted in {n_chunks} chunks of ≤{CHUNK_SIZE} rows")
    header.extend([
        f"",
        f"Lifted to terminal barrier via the matching",
        f"`Cert_m{m}_Q{Q}_S216_Barrier.lean` adapter.",
        f"",
        f"Generated by tools/cert_to_lean_s216.py.",
        f"-/",
        f"",
        f"import CollatzLean4.InverseGraph",
        f"import CollatzLean4.S216",
        f"",
        f"-- Large tables need extra elaboration budget.",
        f"set_option maxHeartbeats 0",
        f"set_option maxRecDepth 500000",
        f"",
        f"namespace CollatzLean4.Admissible.Certificates",
        f"",
        f"open CollatzLean4.Admissible",
        f"",
        f"/-! ### BF closure table for m={m}, Q={Q}, T={T} "
        f"({len(states)} states) -/",
        f"",
    ])

    table_lines = _emit_table(tbl_name, states)

    rest = [
        f"/-- Partial dist function. Unvisited vertices return `none`. -/",
        f"def cert_m{m}_Q{Q}_S216_dist (v : InvVertex) : Option Int :=",
        f"  ({tbl_name}.find? (·.1 = v)).map (·.2)",
        f"",
        f"/-- Start vertex. -/",
        f"def cert_m{m}_Q{Q}_S216_start : InvVertex := InvStart {m}",
        f"",
        f"/-! ### Bool decision procedures -/",
        f"",
        f"/-- Start has dist `0`. -/",
        f"def cert_m{m}_Q{Q}_S216_start_check : Bool :=",
        f"  decide (cert_m{m}_Q{Q}_S216_dist cert_m{m}_Q{Q}_S216_start = some (0 : Int))",
        f"",
        f"/-- No goal in the table has dist `< T`. -/",
        f"def cert_m{m}_Q{Q}_S216_no_goal_check : Bool :=",
        f"  {tbl_name}.all (fun ⟨v, d⟩ =>",
        f"    !(decide (v.c % (3 ^ ({R} + v.j)) = 1 % (3 ^ ({R} + v.j))))",
        f"    || !(decide (d < ({T} : Int))))",
        f"",
        f"/-- Optimistic closure check. -/",
        f"def cert_m{m}_Q{Q}_S216_closed_check : Bool :=",
        f"  {tbl_name}.all (fun ⟨s, d⟩ =>",
        f"    let credit_s : Int := ({Q} : Int) - (s.j : Int)",
        f"    !(decide (d - credit_s < ({T} : Int)))",
        f"    || (outgoingEdges {R} {Q} s).all (fun e =>",
        f"      let v := e.1",
        f"      let w := e.2",
        f"      let nd := d + w",
        f"      let credit_v : Int := ({Q} : Int) - (v.j : Int)",
        f"      !(decide (v.j ≤ {Q}))",
        f"      || !(decide (nd - credit_v < ({T} : Int)))",
        f"      || match cert_m{m}_Q{Q}_S216_dist v with",
        f"         | some d' => decide (d' ≤ nd)",
        f"         | none    => false))",
        f"",
        f"/-! ### Bool proofs via `native_decide` -/",
        f"",
        f"theorem cert_m{m}_Q{Q}_S216_start_holds :",
        f"    cert_m{m}_Q{Q}_S216_start_check = true := by native_decide",
        f"",
        f"theorem cert_m{m}_Q{Q}_S216_no_goal_holds :",
        f"    cert_m{m}_Q{Q}_S216_no_goal_check = true := by native_decide",
        f"",
        f"theorem cert_m{m}_Q{Q}_S216_closed_holds :",
        f"    cert_m{m}_Q{Q}_S216_closed_check = true := by native_decide",
        f"",
        f"end CollatzLean4.Admissible.Certificates",
        f"",
    ]

    return "\n".join(header + table_lines + rest)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python cert_to_lean_s216.py <m> <Q>", file=sys.stderr)
        sys.exit(1)
    m, Q = int(sys.argv[1]), int(sys.argv[2])
    sys.stdout.write(emit_lean_s216(m, Q))
