"""
Exporter: closure_certificate JSON → Lean file using `LocalPotentialCertificate`.

Generates a Lean module that:
  1. Hard-codes the dist table as `Cert_m{m}_Q{Q} : List (InvVertex × Int)`.
  2. Defines `lookup_m{m}_Q{Q}` with sentinel T (threshold) for unvisited vertices.
  3. Defines `closure_check_m{m}_Q{Q} : Bool` and verifies it via `native_decide`.
  4. Defines `no_goal_check_m{m}_Q{Q}` similarly.

The output is a stand-alone Lean module that imports
`CollatzLean4.InverseGraph` and emits the empirical barrier as a decidable
fact. Lifting to a formal `barrier_from_potential` theorem requires the
path-induction lemma (S212 follow-up).

Usage:
  python3 cert_to_lean.py m Q > Cert_m_Q.lean
"""

from __future__ import annotations
import sys
from s202_engine import S202Engine


def emit_lean(m: int, Q: int, max_states: int = 1_000_000) -> str:
    engine = S202Engine(m=m, Q=Q)
    result = engine.search_or_certify(max_states=max_states)

    if result["status"] != "barrier_certificate":
        raise ValueError(f"No certificate: status={result['status']}")

    R = result["R"]
    T = result["threshold"]
    states = result["states"]

    lines = [
        f"/-",
        f"Auto-generated barrier certificate (m={m}, Q={Q}, R={R}, T={T}).",
        f"",
        f"Empirical conclusion: {result['conclusion']}",
        f"",
        f"  - states explored: {len(states)}",
        f"  - generated by tools/cert_to_lean.py",
        f"-/",
        f"",
        f"import CollatzLean4.InverseGraph",
        f"",
        f"namespace CollatzLean4.Admissible.Certificates",
        f"",
        f"open CollatzLean4.Admissible",
        f"",
        f"def Cert_m{m}_Q{Q} : List (InvVertex × Int) :=",
        f"  [",
    ]
    rows = []
    for i, s in enumerate(states):
        prefix = "  , " if i > 0 else "    "
        rows.append(f"{prefix}(⟨{s['j']}, {s['c']}⟩, {s['dist']})")
    lines.extend(rows)
    lines.append("  ]")
    lines.append("")
    lines.append(f"def lookup_m{m}_Q{Q} (v : InvVertex) : Int :=")
    lines.append(f"  ((Cert_m{m}_Q{Q}.find? (·.1 = v)).map (·.2)).getD {T}")
    lines.append("")
    lines.append(f"def closure_check_m{m}_Q{Q} : Bool :=")
    lines.append(f"  Cert_m{m}_Q{Q}.all (fun ⟨s, ds⟩ =>")
    lines.append(f"    (outgoingEdges {R} {Q} s).all (fun (e : InvVertex × Int) =>")
    lines.append(f"      decide (lookup_m{m}_Q{Q} e.1 ≤ ds + e.2)))")
    lines.append("")
    lines.append(f"theorem closure_holds_m{m}_Q{Q} : closure_check_m{m}_Q{Q} = true := by")
    lines.append(f"  native_decide")
    lines.append("")
    lines.append(f"def no_goal_check_m{m}_Q{Q} : Bool :=")
    lines.append(f"  Cert_m{m}_Q{Q}.all (fun (p : InvVertex × Int) =>")
    lines.append(f"    let v := p.1; let d := p.2")
    lines.append(f"    !decide (d < ({T} : Int)) ||")
    lines.append(f"    !decide (v.c % (3 ^ ({R} + v.j)) = 1 % (3 ^ ({R} + v.j))))")
    lines.append("")
    lines.append(f"theorem no_goal_holds_m{m}_Q{Q} : no_goal_check_m{m}_Q{Q} = true := by")
    lines.append(f"  native_decide")
    lines.append("")
    lines.append(f"end CollatzLean4.Admissible.Certificates")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python3 cert_to_lean.py <m> <Q>", file=sys.stderr)
        sys.exit(1)
    m, Q = int(sys.argv[1]), int(sys.argv[2])
    sys.stdout.write(emit_lean(m, Q))
