"""
emit_kappa_cert.py — emit a Lean κ-weighted BF-closure certificate.

Runs the κ-precise optimistic-cut Bellman-Ford (KappaEngine) for (m, Q, T=m),
and if it certifies the barrier (no goal with κ-cost < m), emits a self-contained
Lean file proving `S216BarrierForWords m Q m` via `S216_barrier_for_words_via_kappa`
(the κ route in KappaCert.lean).

Usage:  python emit_kappa_cert.py m Q  > .../Cert_m{m}_Q{Q}_kappa.lean
"""
from __future__ import annotations
import sys
from kappa_precise_probe import KappaEngine


def emit(m: int, Q: int) -> str:
    R = 22 * m + 2
    eng = KappaEngine(m=m, Q=Q, threshold=m)
    res = eng.search_or_certify_bf(max_states=2_000_000)
    if res["status"] != "barrier_certificate":
        raise SystemExit(f"engine returned {res['status']} for m={m},Q={Q}; cannot emit cert")
    states = res["states"]  # list of {j, c, dist, ...}
    nm = f"kappa_m{m}_Q{Q}"
    # --- table ---
    rows = ",\n    ".join(f"(⟨{s['j']}, {s['c']}⟩, {s['dist']})" for s in states)
    L = []
    L.append(f"""/-
Auto-generated κ-precise BF closure certificate (m={m}, Q={Q}, R={R}, T={m}).

  - {len(states)} states explored, κ-weighted optimistic-cut BF self-verified.
  - closure rule: d - (Q - j) < T  (S216 optimistic), κ-weights via `toKappa`.
  - conclusion: every admissible word with q ≤ {Q} in the m={m} S202 cylinder
    has  n_one - n_neg ≥ {m},  hence  defect ≥ {m}.

Generated by tools/emit_kappa_cert.py. Terminal theorem:
  `Cert_m{m}_Q{Q}_kappa.barrier_m{m}_Q{Q}_kappa : S216BarrierForWords {m} {Q} {m}`
-/

import CollatzLean4.InverseGraph
import CollatzLean4.S216
import CollatzLean4.KappaCert

namespace CollatzLean4.Admissible.Certificates

open CollatzLean4.Admissible

/-- κ-weighted BF closure table for m={m}, Q={Q}, T={m}. -/
def {nm}_tbl : List (InvVertex × Int) :=
  [
    {rows}
  ]

/-- Partial κ-dist function. Unvisited vertices return `none`. -/
def {nm}_dist (v : InvVertex) : Option Int :=
  ({nm}_tbl.find? (·.1 = v)).map (·.2)

/-! ### Bool decision procedures -/

def {nm}_start_check : Bool :=
  decide ({nm}_dist (InvStart {m}) = some (0 : Int))

def {nm}_no_goal_check : Bool :=
  {nm}_tbl.all (fun ⟨v, d⟩ =>
    !(decide (v.c % (3 ^ ({R} + v.j)) = 1 % (3 ^ ({R} + v.j))))
    || !(decide (d < ({m} : Int))))

def {nm}_closed_check : Bool :=
  {nm}_tbl.all (fun ⟨s, d⟩ =>
    let credit_s : Int := ({Q} : Int) - (s.j : Int)
    !(decide (d - credit_s < ({m} : Int)))
    || (outgoingEdges {R} {Q} s).all (fun e =>
      let v := e.1
      let w := e.2
      let nd := d + toKappa s v w
      let credit_v : Int := ({Q} : Int) - (v.j : Int)
      !(decide (v.j ≤ {Q}))
      || !(decide (nd - credit_v < ({m} : Int)))
      || match {nm}_dist v with
         | some d' => decide (d' ≤ nd)
         | none    => false))

theorem {nm}_start_holds : {nm}_start_check = true := by native_decide
theorem {nm}_no_goal_holds : {nm}_no_goal_check = true := by native_decide
theorem {nm}_closed_holds : {nm}_closed_check = true := by native_decide

/-! ### Bool → Prop soundness -/

lemma {nm}_dist_some_mem {{v : InvVertex}} {{d : Int}}
    (h : {nm}_dist v = some d) : (v, d) ∈ {nm}_tbl := by
  unfold {nm}_dist at h
  rcases h_eq : {nm}_tbl.find? (·.1 = v) with _ | ⟨v', d'⟩
  · rw [h_eq] at h; simp at h
  · rw [h_eq] at h
    simp at h
    have h_pred := List.find?_some h_eq
    simp at h_pred
    subst h_pred
    subst h
    exact List.mem_of_find?_eq_some h_eq

theorem {nm}_start_sound : {nm}_dist (InvStart {m}) = some 0 :=
  of_decide_eq_true {nm}_start_holds

theorem {nm}_no_goal_sound :
    ∀ v d, {nm}_dist v = some d → InvVertex.IsGoal v {R} → ¬ d < ({m} : Int) := by
  intro v d h_dist h_goal h_lt
  have h_mem := {nm}_dist_some_mem h_dist
  have h := {nm}_no_goal_holds
  unfold {nm}_no_goal_check at h
  rw [List.all_eq_true] at h
  have h_p := h (v, d) h_mem
  unfold InvVertex.IsGoal at h_goal
  simp only [Bool.or_eq_true, Bool.not_eq_true', decide_eq_false_iff_not] at h_p
  exact h_p.elim (fun hg => hg h_goal) (fun hd => hd h_lt)

theorem {nm}_closed_sound :
    ∀ v d, {nm}_dist v = some d → relevant {Q} ({m} : Int) v d →
      ∀ e ∈ outgoingEdges {R} {Q} v, e.1.j ≤ {Q} →
        relevant {Q} ({m} : Int) e.1 (d + toKappa v e.1 e.2) →
        ∃ d', {nm}_dist e.1 = some d' ∧ d' ≤ d + toKappa v e.1 e.2 := by
  intro v d h_dist h_v_rel e h_e_in h_e_j_le h_e_rel
  have h_v_mem := {nm}_dist_some_mem h_dist
  have h := {nm}_closed_holds
  unfold {nm}_closed_check at h
  rw [List.all_eq_true] at h
  have h_p_v := h (v, d) h_v_mem
  simp only [Bool.or_eq_true, Bool.not_eq_true', decide_eq_false_iff_not] at h_p_v
  rcases h_p_v with h_v_not_rel | h_inner
  · exfalso
    apply h_v_not_rel
    have := h_v_rel
    unfold relevant credit at this
    exact this
  rw [List.all_eq_true] at h_inner
  have h_e_p := h_inner e h_e_in
  simp only [Bool.or_eq_true, Bool.not_eq_true', decide_eq_false_iff_not] at h_e_p
  rcases h_e_p with (h_e_j_neg | h_e_not_rel) | h_match
  · exact (h_e_j_neg h_e_j_le).elim
  · have := h_e_rel
    unfold relevant credit at this
    exact (h_e_not_rel this).elim
  rcases h_dist_e : {nm}_dist e.1 with _ | d'
  · exfalso
    rw [h_dist_e] at h_match
    simp at h_match
  · rw [h_dist_e] at h_match
    refine ⟨d', rfl, ?_⟩
    simpa using h_match

/-! ### Terminal κ barrier -/

theorem {nm}_barrier_internal (u : Word)
    (h_q : (evalWord u).q ≤ {Q})
    (h_cyl : (evalWord u).n % (3 ^ {R}) = aS202 % (3 ^ {R})) :
    ({m} : Int) ≤ defect (evalWord u) :=
  S216_barrier_for_words_via_kappa {nm}_dist
    {nm}_start_sound {nm}_no_goal_sound {nm}_closed_sound u h_q h_cyl

end CollatzLean4.Admissible.Certificates

namespace Cert_m{m}_Q{Q}_kappa

open CollatzLean4.Admissible
open CollatzLean4.Admissible.Certificates

/-- **`barrier_m{m}_Q{Q}_kappa : S216BarrierForWords {m} {Q} {m}`** — the S202
cylinder accessibility barrier `𝒞^←_{{S202}}({m}, {Q}) ≥ {m}` proved through the
κ-precise (one_edges − τ=1 zero_edges ≥ m) route, end-to-end via the
non-circular bounded chain. -/
theorem barrier_m{m}_Q{Q}_kappa : S216BarrierForWords {m} {Q} {m} := by
  intro u h_q h_cyl
  exact {nm}_barrier_internal u h_q h_cyl

end Cert_m{m}_Q{Q}_kappa
""")
    return "".join(L)


if __name__ == "__main__":
    m = int(sys.argv[1]) if len(sys.argv) > 1 else 1
    Q = int(sys.argv[2]) if len(sys.argv) > 2 else 1
    sys.stdout.write(emit(m, Q))
