"""gen_formalization_yaml.py — regenerate AxiomAudit.lean and formalization.yaml.

Pipeline (all machine-generated, no hand-maintained claims):
  1. Extract every \\lean{...} name cited in paper1/main.tex.
  2. Emit CollatzLean4/CollatzLean4/AxiomAudit.lean with one `#print axioms`
     probe per cited declaration (module names and Lean axioms filtered out).
  3. (caller) `lake build CollatzLean4.AxiomAudit` and feed the log back via
     --parse <logfile>: the script then writes formalization.yaml with the
     verified axiom set of every cited declaration and the list of modules
     that genuinely use `native_decide` (comment-stripped scan).

Usage:
  python tools/gen_formalization_yaml.py            # step 2 (write the probe file)
  lake build CollatzLean4.AxiomAudit > audit.log    # step 3a (from CollatzLean4/)
  python tools/gen_formalization_yaml.py --parse audit.log   # step 3b
"""
import re, io, glob, os, sys, json, subprocess, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEAN_DIR = os.path.join(ROOT, 'CollatzLean4', 'CollatzLean4')
TRIO = {'propext', 'Classical.choice', 'Quot.sound'}

IMPORTS = ['AdmissibleBasic', 'Defect', 'S202Cylinders', 'PathWordCorrespondence',
           'S212Forward', 'AnalyticBarrier', 'KappaSplitReduction', 'LadderExists',
           'LadderRefutation', 'ReachUnits', 'OneEdgeMod9', 'AttractorNoGo',
           'HybridPotentialNoGo', 'BitlenPotential', 'FaithfulBarrier', 'AS202Lift',
           'DiscreteLog', 'LTEBound', 'RhoTransitionLaws', 'BridgeTruth', 'ClosedWalk',
           'CycleEquation', 'CycleReduction', 'CollatzBridge', 'F2Collatz',
           'SyracuseMeasure']


def cited_declarations():
    tex = io.open(os.path.join(ROOT, 'paper1', 'main.tex'), encoding='utf-8').read()
    modules = {os.path.basename(f)[:-5] for f in glob.glob(os.path.join(LEAN_DIR, '*.lean'))}
    skip = {'propext', 'Classical.choice', 'Quot.sound', 'native_decide', 'Q10', 'sorry'}
    names = set()
    for m in re.findall(r'\\lean\{([^}]*)\}', tex):
        m = m.replace('\\_', '_').replace('\\#', '#')
        for part in re.split(r'[,]', m):
            part = part.strip().rstrip('.')
            if (not part or part.startswith('#') or '/' in part or '*' in part
                    or part.isdigit() or '<' in part):
                continue
            part = part.replace('.lean', '')
            if part in modules or part in skip:
                continue
            names.add(part)
    return sorted(names)


def write_probe(decls):
    hdr = ('/-\nAxiomAudit --- machine-generated per-declaration axiom audit of every '
           'Lean name cited\nin Paper 1 (paper1/main.tex).  NOT imported by the root '
           'module; build on demand:\n\n    lake build CollatzLean4.AxiomAudit\n\n'
           'Regenerated by tools/gen_formalization_yaml.py, which also turns the build '
           'log into\nformalization.yaml.  Acceptance criterion: every cited declaration '
           'depends on at most\n{propext, Classical.choice, Quot.sound}.\n-/\n')
    body = hdr + '\n'.join('import CollatzLean4.%s' % m for m in IMPORTS)
    body += '\n\nopen CollatzLean4.Admissible CollatzLean4.F2 in\nsection\n'
    for d in decls:
        body += '#print axioms %s\n' % d
    body += 'end\n'
    io.open(os.path.join(LEAN_DIR, 'AxiomAudit.lean'), 'w', encoding='utf-8',
            newline='\n').write(body)
    print('AxiomAudit.lean written with %d probes' % len(decls))


def strip_comments(src):
    out, i, depth = [], 0, 0
    while i < len(src):
        if src.startswith('/-', i):
            depth += 1
            i += 2
            continue
        if depth and src.startswith('-/', i):
            depth -= 1
            i += 2
            continue
        if depth:
            i += 1
            continue
        if src.startswith('--', i):
            j = src.find('\n', i)
            i = len(src) if j < 0 else j
            continue
        out.append(src[i])
        i += 1
    return ''.join(out)


def native_decide_modules():
    out = []
    for f in sorted(glob.glob(os.path.join(LEAN_DIR, '*.lean'))):
        code = strip_comments(io.open(f, encoding='utf-8').read())
        if re.search(r'\bnative_decide\b', code):
            out.append(os.path.basename(f)[:-5])
    return out


def sorry_count():
    n = 0
    for f in glob.glob(os.path.join(LEAN_DIR, '*.lean')):
        code = strip_comments(io.open(f, encoding='utf-8').read())
        n += len(re.findall(r'\bsorry\b', code))
    return n


def parse_log(path):
    txt = io.open(path, encoding='utf-8', errors='replace').read()
    res = {}
    for m in re.finditer(r"'([^']+)' depends on axioms: \[([^\]]*)\]", txt):
        full, axs = m.group(1), [a.strip() for a in m.group(2).split(',') if a.strip()]
        res[full] = axs
    for m in re.finditer(r"'([^']+)' does not depend on any axioms", txt):
        res[m.group(1)] = []
    return res


def write_yaml(audit):
    toolchain = io.open(os.path.join(ROOT, 'CollatzLean4', 'lean-toolchain'),
                        encoding='utf-8').read().strip()
    manifest = json.load(io.open(os.path.join(ROOT, 'CollatzLean4', 'lake-manifest.json'),
                                 encoding='utf-8'))
    mathlib_rev = next(p['rev'] for p in manifest['packages'] if p['name'] == 'mathlib')
    commit = subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=ROOT,
                            capture_output=True, text=True).stdout.strip()
    nd = native_decide_modules()
    clean, dirty = [], []
    for full in sorted(audit):
        extra = sorted(set(audit[full]) - TRIO)
        (dirty if extra else clean).append((full, audit[full], extra))

    L = []
    A = L.append
    A('# formalization.yaml --- machine-generated disclosure manifest.')
    A('# Regenerate: python tools/gen_formalization_yaml.py  (see its docstring).')
    A('# Generated %s at commit %s.'
      % (datetime.date.today().isoformat(), commit[:12]))
    A('')
    A('project:')
    A('  name: collatz-admissible-tree')
    A('  title: >-')
    A('    Machine-checked obstructions for potential-based approaches to the')
    A('    Collatz conjecture, with closed-form bounded barriers')
    A('  repository: https://github.com/benetandujar72/collatz-admissible-tree')
    A('  paper: paper1/main.pdf  # arXiv submission tag arxiv-v1')
    A('  status: complete (paper v1); research programme ongoing')
    A('')
    A('authors:')
    A('  - name: Benet Andújar Guardado')
    A('    role: >-')
    A('      sole human author; set the programme, the targets and the acceptance')
    A('      criteria; validated all mathematical content; takes full responsibility')
    A('    email: bandujar@edutac.es')
    A('ai_assistance:')
    A('  tool: Claude (Anthropic), Opus-class and successor models, sessions 2025-2026')
    A('  role: >-')
    A('    drafted Lean proofs, numerical gates and refactors under the funnel')
    A('    methodology (numerical gate -> adversarial verification -> Lean')
    A('    authentication); two plausible AI-produced intermediate claims were')
    A('    refuted at the adversarial stage and never entered the corpus')
    A('  disclosure: >-')
    A('    every commit carries a Co-Authored-By trailer; the paper discloses the')
    A('    collaboration in the acknowledgements and in Section 9 (methodology,')
    A('    evidence tiers T1/T1\'/T2/T3)')
    A('  trust_basis: >-')
    A('    correctness rests on the Lean kernel and the stated axioms, not on')
    A('    either collaborator')
    A('')
    A('toolchain:')
    A('  lean: %s' % toolchain)
    A('  mathlib: %s' % mathlib_rev)
    A('  build: lake build CollatzLean4.<Module>   # narrow targets; see appendix B')
    A('')
    A('verification:')
    A('  modules: %d' % len(glob.glob(os.path.join(LEAN_DIR, '*.lean'))))
    A('  sorry_count: %d   # comment-stripped scan, tools/gen_formalization_yaml.py'
      % sorry_count())
    A('  axiom_policy: >-')
    A('    every declaration cited in the paper must depend on at most')
    A('    {propext, Classical.choice, Quot.sound}; verified per declaration by')
    A('    CollatzLean4/AxiomAudit.lean (machine-generated, see below)')
    A('  native_decide:')
    A('    policy: >-')
    A('      quarantined to legacy exploratory strata and per-instance certificate')
    A('      modules (paper evidence tier T1\'); nothing cited in the paper depends')
    A('      on them (see audit)')
    A('    modules_using_it:')
    for m in nd:
        A('      - %s' % m)
    A('')
    A('axiom_audit:')
    A('  method: >-')
    A('    lake build CollatzLean4.AxiomAudit emits one "#print axioms" per cited')
    A('    declaration; this file records the result verbatim')
    A('  declarations_audited: %d' % len(audit))
    A('  declarations_clean: %d   # axioms subset of the standard trio' % len(clean))
    A('  declarations_flagged: %d' % len(dirty))
    if dirty:
        A('  flagged:')
        for full, axs, extra in dirty:
            A('    - name: %s' % full)
            A('      axioms: [%s]' % ', '.join(axs))
    A('  clean:')
    for full, axs, _ in clean:
        A('    - %s' % full)
    A('')
    A('key_results:  # informal statement -> Lean name (all audited above)')
    A('  - { lean: collatz_F2X, informal: "every nonzero f in F2[x] reaches 1 under the Collatz analogue (HMYZ 2008); believed first formalization" }')
    A('  - { lean: kappa_barrier_m1_Q7, informal: "closed-form bit-length potential proves the bounded kappa-barrier, m=1, Q<=7" }')
    A('  - { lean: no_linear_size_potential_m1_Q8, informal: "no rational linear (1,j,size) potential satisfies the contract at (1,8): the wall is exact" }')
    A('  - { lean: linear_size_potential_m1_Q7, informal: "the linear relaxation of PhiBitlen satisfies the universal contract at (1,7): the wall is exact on both sides" }')
    A('  - { lean: no_hybrid_potential_m1_Q8, informal: "adding singular attractor poles nu3(c-+1) does not move the wall: the enriched class is already dead at (1,8)" }')
    A('  - { lean: invReachable_units, informal: "every unit cylinder mod 3^t is reachable: no separating congruence invariant exists" }')
    A('  - { lean: no_decaying_modulus_corrector, informal: "no 3-adically continuous real potential satisfies the contract (m <= omega(22+Q))" }')
    A('  - { lean: not_blockBoundaryExists, informal: "the canonical split devices for the per-block induction are refuted (astronomical one-edge ladder)" }')
    A('  - { lean: syr_cycle_window, informal: "every nontrivial Syracuse m-cycle has m*log2(3) < A < 2m" }')
    A('  - { lean: syr_no_cycle_below_16266, informal: "conditional on verification up to 2^29: no Syracuse cycle of period < 16266 (Eliahou-Hercher pipeline, kernel-checked)" }')
    A('')
    A('honest_scope: >-')
    A('  The paper claims no progress on the Collatz conjecture itself.  Its content')
    A('  is a machine-checked obstruction map for potential-based strategies on the')
    A('  inverse cylinder tree, the strongest closed-form barriers those')
    A('  obstructions permit, a verified cycle pipeline, and the function-field')
    A('  control experiment.')
    A('')
    out = '\n'.join(L) + '\n'
    io.open(os.path.join(ROOT, 'formalization.yaml'), 'w', encoding='utf-8',
            newline='\n').write(out)
    print('formalization.yaml written: %d audited, %d clean, %d flagged'
          % (len(audit), len(clean), len(dirty)))
    for full, axs, extra in dirty:
        print('  FLAGGED:', full, '->', extra)


if __name__ == '__main__':
    if '--parse' in sys.argv:
        log = sys.argv[sys.argv.index('--parse') + 1]
        audit = parse_log(log)
        if not audit:
            print('no audit lines found in', log)
            sys.exit(1)
        write_yaml(audit)
    else:
        decls = cited_declarations()
        write_probe(decls)
