/-
AxiomAudit --- machine-generated per-declaration axiom audit of every Lean name cited
in Paper 1 (paper1/main.tex).  NOT imported by the root module; build on demand:

    lake build CollatzLean4.AxiomAudit

Regenerated by tools/gen_formalization_yaml.py, which also turns the build log into
formalization.yaml.  Acceptance criterion: every cited declaration depends on at most
{propext, Classical.choice, Quot.sound}.
-/
import CollatzLean4.AdmissibleBasic
import CollatzLean4.Defect
import CollatzLean4.S202Cylinders
import CollatzLean4.PathWordCorrespondence
import CollatzLean4.S212Forward
import CollatzLean4.AnalyticBarrier
import CollatzLean4.KappaSplitReduction
import CollatzLean4.LadderExists
import CollatzLean4.LadderRefutation
import CollatzLean4.ReachUnits
import CollatzLean4.OneEdgeMod9
import CollatzLean4.AttractorNoGo
import CollatzLean4.HybridPotentialNoGo
import CollatzLean4.BitlenPotential
import CollatzLean4.FaithfulBarrier
import CollatzLean4.AS202Lift
import CollatzLean4.DiscreteLog
import CollatzLean4.LTEBound
import CollatzLean4.RhoTransitionLaws
import CollatzLean4.BridgeTruth
import CollatzLean4.ClosedWalk
import CollatzLean4.CycleEquation
import CollatzLean4.CycleReduction
import CollatzLean4.CollatzBridge
import CollatzLean4.F2Collatz
import CollatzLean4.SyracuseMeasure

open CollatzLean4.Admissible CollatzLean4.F2 in
section
#print axioms BlockBoundaryExists
#print axioms CollatzVerifiedUpTo
#print axioms EffectiveLinearForm
#print axioms FirstMPrecisionSuffixPositive
#print axioms InX
#print axioms InvEdgeOne
#print axioms InvEdgeZero
#print axioms InvKappaPreciseEdge
#print axioms InvPathCounts
#print axioms InvPathCounts.weight_lower_bound
#print axioms InvStart
#print axioms InvStartAt
#print axioms InvVertex
#print axioms InvVertex.IsGoal
#print axioms KappaPathSplit
#print axioms PhiBitlen
#print axioms S202_actual_edge_count_bounded_of_kappa_precise_barrier_bounded
#print axioms S202_kappa_precise_barrier_bounded
#print axioms S202_kappa_precise_barrier_bounded_from_potential
#print axioms S202_one_edge_count_conjecture_iff_defect_barrier
#print axioms S202_slope_barrier_from_actual_edge_count_bounded
#print axioms S202_translation_identity
#print axioms S212_forward
#print axioms SyrVerifiedUpTo
#print axioms WPath_kappa_weight_ge_potential_bounded
#print axioms aS202
#print axioms aS202_at
#print axioms aS202_decomp
#print axioms attractor_chain
#print axioms closed_oneWalk_weight_ge_order
#print axioms collatzT_iterate_natDegree_le
#print axioms collatz_F2X
#print axioms collatz_no_cycle_below_16266
#print axioms collatz_no_cycle_below_359
#print axioms deep_edge
#print axioms evalWord
#print axioms evalWord_translation_identity
#print axioms evenStep_natDegree
#print axioms fastPowAux
#print axioms fastPow_eq
#print axioms invReachable_hits_trap
#print axioms invReachable_units
#print axioms invReachable_zero_lift
#print axioms kappaPathSplit_of_block
#print axioms kappaPathSplit_yields_piecewise_bounds
#print axioms kappa_barrier_at_m2_Q16
#print axioms kappa_barrier_at_m3_Q23
#print axioms kappa_barrier_m1_Q7
#print axioms kappa_barrier_of_sum_le_eight
#print axioms kappa_bounded_barrier_bitlen
#print axioms kappa_bounded_barrier_bitlen_from
#print axioms ladder_exists
#print axioms linear_size_potential_m1_Q7
#print axioms mediant_period_bound
#print axioms mod6_of_two_pow_mod9_seven
#print axioms no_decaying_modulus_corrector
#print axioms no_hybrid_potential_m1_Q8
#print axioms no_hybrid_potential_m1_Q9
#print axioms no_linear_size_potential_m1_Q8
#print axioms not_blockBoundaryExists
#print axioms not_firstMPrecisionSuffixPositive
#print axioms nu3_aS202_sub_one
#print axioms oddStep_coeff_zero
#print axioms oddStep_natDegree
#print axioms oneEdge_deepjump_iff
#print axioms oneEdge_deepjump_source_four
#print axioms oneEdge_size_le
#print axioms oneEdge_source_mod9_in_four_seven
#print axioms orderOf_two_zmod_three_pow
#print axioms outerBlockIncrement_false
#print axioms plateau_exit
#print axioms plateau_step_identity
#print axioms size_three_mul_add_one
#print axioms size_two_pow_mul
#print axioms syrVerified_of_collatzVerified
#print axioms syr_cycle_elements_above_frontier
#print axioms syr_cycle_gap_eq
#print axioms syr_cycle_gap_mul_frontier_lt
#print axioms syr_cycle_mul_equation
#print axioms syr_cycle_window
#print axioms syr_master_corridor
#print axioms syr_mediant_exclusion
#print axioms syr_no_cycle_below_16266
#print axioms syr_no_cycle_below_359
#print axioms syr_no_nontrivial_4cycle
#print axioms syr_no_nontrivial_fixedpoint
#print axioms tau
#print axioms tau1_attractor
#print axioms tau1_attractor_nu3
#print axioms tau2_attractor
#print axioms tau2_attractor_nu3
#print axioms tau_le_four
#print axioms two_pow_tau_mul_mod9
#print axioms uniform_kappa_barrier_of_block
#print axioms uniform_slope_barrier_of_block
#print axioms zeroEdge_size_le
end
