/-
Auto-generated κ-precise BF closure certificate (m=1, Q=1, R=24, T=1).

  - 5 states explored, κ-weighted optimistic-cut BF self-verified.
  - closure rule: d - (Q - j) < T  (S216 optimistic), κ-weights via `toKappa`.
  - conclusion: every admissible word with q ≤ 1 in the m=1 S202 cylinder
    has  n_one - n_neg ≥ 1,  hence  defect ≥ 1.

Generated by tools/emit_kappa_cert.py. Terminal theorem:
  `Cert_m1_Q1_kappa.barrier_m1_Q1_kappa : S216BarrierForWords 1 1 1`
-/

import CollatzLean4.InverseGraph
import CollatzLean4.S216
import CollatzLean4.KappaCert

namespace CollatzLean4.Admissible.Certificates

open CollatzLean4.Admissible

/-- κ-weighted BF closure table for m=1, Q=1, T=1. -/
def kappa_m1_Q1_tbl : List (InvVertex × Int) :=
  [
    (⟨0, 31381059610⟩, 0),
    (⟨1, 329501125895⟩, 0),
    (⟨1, 470715894137⟩, -1),
    (⟨1, 588394867669⟩, 0),
    (⟨1, 659002251790⟩, 0)
  ]

/-- Partial κ-dist function. Unvisited vertices return `none`. -/
def kappa_m1_Q1_dist (v : InvVertex) : Option Int :=
  (kappa_m1_Q1_tbl.find? (·.1 = v)).map (·.2)

/-! ### Bool decision procedures -/

def kappa_m1_Q1_start_check : Bool :=
  decide (kappa_m1_Q1_dist (InvStart 1) = some (0 : Int))

def kappa_m1_Q1_no_goal_check : Bool :=
  kappa_m1_Q1_tbl.all (fun ⟨v, d⟩ =>
    !(decide (v.c % (3 ^ (24 + v.j)) = 1 % (3 ^ (24 + v.j))))
    || !(decide (d < (1 : Int))))

def kappa_m1_Q1_closed_check : Bool :=
  kappa_m1_Q1_tbl.all (fun ⟨s, d⟩ =>
    let credit_s : Int := (1 : Int) - (s.j : Int)
    !(decide (d - credit_s < (1 : Int)))
    || (outgoingEdges 24 1 s).all (fun e =>
      let v := e.1
      let w := e.2
      let nd := d + toKappa s v w
      let credit_v : Int := (1 : Int) - (v.j : Int)
      !(decide (v.j ≤ 1))
      || !(decide (nd - credit_v < (1 : Int)))
      || match kappa_m1_Q1_dist v with
         | some d' => decide (d' ≤ nd)
         | none    => false))

theorem kappa_m1_Q1_start_holds : kappa_m1_Q1_start_check = true := by native_decide
theorem kappa_m1_Q1_no_goal_holds : kappa_m1_Q1_no_goal_check = true := by native_decide
theorem kappa_m1_Q1_closed_holds : kappa_m1_Q1_closed_check = true := by native_decide

/-! ### Bool → Prop soundness -/

lemma kappa_m1_Q1_dist_some_mem {v : InvVertex} {d : Int}
    (h : kappa_m1_Q1_dist v = some d) : (v, d) ∈ kappa_m1_Q1_tbl := by
  unfold kappa_m1_Q1_dist at h
  rcases h_eq : kappa_m1_Q1_tbl.find? (·.1 = v) with _ | ⟨v', d'⟩
  · rw [h_eq] at h; simp at h
  · rw [h_eq] at h
    simp at h
    have h_pred := List.find?_some h_eq
    simp at h_pred
    subst h_pred
    subst h
    exact List.mem_of_find?_eq_some h_eq

theorem kappa_m1_Q1_start_sound : kappa_m1_Q1_dist (InvStart 1) = some 0 :=
  of_decide_eq_true kappa_m1_Q1_start_holds

theorem kappa_m1_Q1_no_goal_sound :
    ∀ v d, kappa_m1_Q1_dist v = some d → InvVertex.IsGoal v 24 → ¬ d < (1 : Int) := by
  intro v d h_dist h_goal h_lt
  have h_mem := kappa_m1_Q1_dist_some_mem h_dist
  have h := kappa_m1_Q1_no_goal_holds
  unfold kappa_m1_Q1_no_goal_check at h
  rw [List.all_eq_true] at h
  have h_p := h (v, d) h_mem
  unfold InvVertex.IsGoal at h_goal
  simp only [Bool.or_eq_true, Bool.not_eq_true', decide_eq_false_iff_not] at h_p
  exact h_p.elim (fun hg => hg h_goal) (fun hd => hd h_lt)

theorem kappa_m1_Q1_closed_sound :
    ∀ v d, kappa_m1_Q1_dist v = some d → relevant 1 (1 : Int) v d →
      ∀ e ∈ outgoingEdges 24 1 v, e.1.j ≤ 1 →
        relevant 1 (1 : Int) e.1 (d + toKappa v e.1 e.2) →
        ∃ d', kappa_m1_Q1_dist e.1 = some d' ∧ d' ≤ d + toKappa v e.1 e.2 := by
  intro v d h_dist h_v_rel e h_e_in h_e_j_le h_e_rel
  have h_v_mem := kappa_m1_Q1_dist_some_mem h_dist
  have h := kappa_m1_Q1_closed_holds
  unfold kappa_m1_Q1_closed_check at h
  rw [List.all_eq_true] at h
  have h_p_v := h (v, d) h_v_mem
  simp only [Bool.or_eq_true, Bool.not_eq_true', decide_eq_false_iff_not] at h_p_v
  rcases h_p_v with h_v_not_rel | h_inner
  · exfalso
    apply h_v_not_rel
    have := h_v_rel
    unfold relevant credit at this
    exact this
  rw [List.all_eq_true] at h_inner
  have h_e_p := h_inner e h_e_in
  simp only [Bool.or_eq_true, Bool.not_eq_true', decide_eq_false_iff_not] at h_e_p
  rcases h_e_p with (h_e_j_neg | h_e_not_rel) | h_match
  · exact (h_e_j_neg h_e_j_le).elim
  · have := h_e_rel
    unfold relevant credit at this
    exact (h_e_not_rel this).elim
  rcases h_dist_e : kappa_m1_Q1_dist e.1 with _ | d'
  · exfalso
    rw [h_dist_e] at h_match
    simp at h_match
  · rw [h_dist_e] at h_match
    refine ⟨d', rfl, ?_⟩
    simpa using h_match

/-! ### Terminal κ barrier -/

theorem kappa_m1_Q1_barrier_internal (u : Word)
    (h_q : (evalWord u).q ≤ 1)
    (h_cyl : (evalWord u).n % (3 ^ 24) = aS202 % (3 ^ 24)) :
    (1 : Int) ≤ defect (evalWord u) :=
  S216_barrier_for_words_via_kappa kappa_m1_Q1_dist
    kappa_m1_Q1_start_sound kappa_m1_Q1_no_goal_sound kappa_m1_Q1_closed_sound u h_q h_cyl

end CollatzLean4.Admissible.Certificates

namespace Cert_m1_Q1_kappa

open CollatzLean4.Admissible
open CollatzLean4.Admissible.Certificates

/-- **`barrier_m1_Q1_kappa : S216BarrierForWords 1 1 1`** — the S202
cylinder accessibility barrier `𝒞^←_{S202}(1, 1) ≥ 1` proved through the
κ-precise (one_edges − τ=1 zero_edges ≥ m) route, end-to-end via the
non-circular bounded chain. -/
theorem barrier_m1_Q1_kappa : S216BarrierForWords 1 1 1 := by
  intro u h_q h_cyl
  exact kappa_m1_Q1_barrier_internal u h_q h_cyl

end Cert_m1_Q1_kappa
