/-
Auto-generated S216 BF closure certificate (m=1, Q=3, R=24, T=1).

  - 35 states explored, BF self-verified ✓
  - closure rule: d - (Q - j) < T  (S216 optimistic)
  - empirical conclusion: 𝒞^←_{S202}(m=1, Q=3) ≥ 1

Lift to formal Lean barrier requires the S216CertBool → S216Cert
adapter (see HANDOFF_S216.md §3.2). With the adapter in place,
`S216_barrier_for_words` yields:

  ∀ u : Word, q(u) ≤ 3 → n(u) ≡ aS202 (mod 3^24) → 1 ≤ defect(evalWord u)

Generated by tools/cert_to_lean_s216.py.
-/

import CollatzLean4.InverseGraph
import CollatzLean4.S216

namespace CollatzLean4.Admissible.Certificates

open CollatzLean4.Admissible

/-- BF closure table for m=1, Q=3, T=1. -/
def cert_m1_Q3_S216_tbl : List (InvVertex × Int) :=
  [
    (⟨0, 31381059610⟩, 0)
  , (⟨1, 329501125895⟩, 1)
  , (⟨1, 470715894137⟩, -1)
  , (⟨1, 588394867669⟩, 2)
  , (⟨1, 659002251790⟩, 0)
  , (⟨2, 353036920603⟩, -1)
  , (⟨2, 494251688843⟩, 0)
  , (⟨2, 706073841206⟩, -2)
  , (⟨2, 723725687233⟩, 1)
  , (⟨2, 882592301504⟩, 1)
  , (⟨2, 1129718145925⟩, 0)
  , (⟨2, 1447451374466⟩, 0)
  , (⟨2, 1518058758586⟩, 1)
  , (⟨2, 1835791987127⟩, 1)
  , (⟨2, 2259436291850⟩, -1)
  , (⟨3, 529555380905⟩, -2)
  , (⟨3, 741377533265⟩, -1)
  , (⟨3, 847288609444⟩, 0)
  , (⟨3, 1085588530850⟩, 0)
  , (⟨3, 1694577218888⟩, -1)
  , (⟨3, 2038788216473⟩, 0)
  , (⟨3, 2753687980691⟩, 0)
  , (⟨3, 3468587744908⟩, 0)
  , (⟨3, 3706887666314⟩, 0)
  , (⟨3, 4077576432946⟩, -1)
  , (⟨3, 4183487509126⟩, 0)
  , (⟨3, 4871909504303⟩, -3)
  , (⟨3, 5136687194750⟩, 0)
  , (⟨3, 5983975804193⟩, -1)
  , (⟨3, 6089886880373⟩, 0)
  , (⟨3, 6248753494645⟩, -2)
  , (⟨3, 6804786644590⟩, 0)
  , (⟨3, 6937175489816⟩, -1)
  , (⟨3, 7201953180269⟩, -2)
  , (⟨3, 7413775332628⟩, -1)
  ]

/-- Partial dist function. Unvisited vertices return `none`. -/
def cert_m1_Q3_S216_dist (v : InvVertex) : Option Int :=
  (cert_m1_Q3_S216_tbl.find? (·.1 = v)).map (·.2)

/-- Start vertex. -/
def cert_m1_Q3_S216_start : InvVertex := InvStart 1

/-! ### Bool decision procedures -/

/-- Start has dist `0`. -/
def cert_m1_Q3_S216_start_check : Bool :=
  decide (cert_m1_Q3_S216_dist cert_m1_Q3_S216_start = some (0 : Int))

/-- No goal in the table has dist `< T`. -/
def cert_m1_Q3_S216_no_goal_check : Bool :=
  cert_m1_Q3_S216_tbl.all (fun ⟨v, d⟩ =>
    !(decide (v.c % (3 ^ (24 + v.j)) = 1 % (3 ^ (24 + v.j))))
    || !(decide (d < (1 : Int))))

/-- Optimistic closure check: every relevant `(s, d)` has every
outgoing edge with relevant target satisfying `dist(target) ≤ d + ω`. -/
def cert_m1_Q3_S216_closed_check : Bool :=
  cert_m1_Q3_S216_tbl.all (fun ⟨s, d⟩ =>
    let credit_s : Int := (3 : Int) - (s.j : Int)
    -- Only enforce closure on relevant labels.
    !(decide (d - credit_s < (1 : Int)))
    || (outgoingEdges 24 3 s).all (fun e =>
      let v := e.1
      let w := e.2
      let nd := d + w
      let credit_v : Int := (3 : Int) - (v.j : Int)
      -- Skip closure on non-relevant targets or oversized j.
      !(decide (v.j ≤ 3))
      || !(decide (nd - credit_v < (1 : Int)))
      || match cert_m1_Q3_S216_dist v with
         | some d' => decide (d' ≤ nd)
         | none    => false))

/-! ### Bool proofs via `native_decide` -/

theorem cert_m1_Q3_S216_start_holds :
    cert_m1_Q3_S216_start_check = true := by native_decide

theorem cert_m1_Q3_S216_no_goal_holds :
    cert_m1_Q3_S216_no_goal_check = true := by native_decide

theorem cert_m1_Q3_S216_closed_holds :
    cert_m1_Q3_S216_closed_check = true := by native_decide

/-! ### Wiring to `S216Cert` requires the adapter

With `S216CertBool_to_S216Cert` (open: see HANDOFF_S216.md §3.2):

  def cert_m1_Q3_S216 : S216Cert 24 3 (1 : Int) :=
    S216CertBool_to_S216Cert ⟨...⟩

Then `S216_barrier_for_words cert_m1_Q3_S216 (rfl) u h_q h_cyl`
closes the cylinder barrier for m=1, Q=3, T=1.
-/

end CollatzLean4.Admissible.Certificates
