/-
Auto-generated κ-precise BF closure certificate (m=1, Q=3, R=24, T=1).

  - 137 states explored, κ-weighted optimistic-cut BF self-verified.
  - closure rule: d - (Q - j) < T  (S216 optimistic), κ-weights via `toKappa`.
  - conclusion: every admissible word with q ≤ 3 in the m=1 S202 cylinder
    has  n_one - n_neg ≥ 1,  hence  defect ≥ 1.

Generated by tools/emit_kappa_cert.py. Terminal theorem:
  `Cert_m1_Q3_kappa.barrier_m1_Q3_kappa : S216BarrierForWords 1 3 1`
-/

import CollatzLean4.InverseGraph
import CollatzLean4.S216
import CollatzLean4.KappaCert

namespace CollatzLean4.Admissible.Certificates

open CollatzLean4.Admissible

/-- κ-weighted BF closure table for m=1, Q=3, T=1. -/
def kappa_m1_Q3_tbl : List (InvVertex × Int) :=
  [
    (⟨0, 31381059610⟩, 0),
    (⟨1, 179460434639⟩, 2),
    (⟨1, 329501125895⟩, 0),
    (⟨1, 340165782871⟩, 2),
    (⟨1, 358920869278⟩, 1),
    (⟨1, 470715894137⟩, -1),
    (⟨1, 513374522041⟩, 2),
    (⟨1, 588394867669⟩, 0),
    (⟨1, 659002251790⟩, 0),
    (⟨1, 680331565742⟩, 2),
    (⟨1, 717841738556⟩, 1),
    (⟨2, 27581009422⟩, 1),
    (⟨2, 55162018844⟩, 1),
    (⟨2, 110324037688⟩, 0),
    (⟨2, 220648075376⟩, 0),
    (⟨2, 269190651959⟩, 1),
    (⟨2, 353036920603⟩, -1),
    (⟨2, 441296150752⟩, 0),
    (⟨2, 494251688843⟩, -1),
    (⟨2, 510248674307⟩, 1),
    (⟨2, 547207226932⟩, 1),
    (⟨2, 706073841206⟩, -2),
    (⟨2, 723725687233⟩, 0),
    (⟨2, 759029379293⟩, 1),
    (⟨2, 770061783062⟩, 1),
    (⟨2, 882592301504⟩, -1),
    (⟨2, 904657109041⟩, 1),
    (⟨2, 1048078358035⟩, 1),
    (⟨2, 1094414453864⟩, 1),
    (⟨2, 1129718145925⟩, 0),
    (⟨2, 1157299155346⟩, 1),
    (⟨2, 1447451374466⟩, 0),
    (⟨2, 1518058758586⟩, 0),
    (⟨2, 1632795757781⟩, 0),
    (⟨2, 1650447603811⟩, 1),
    (⟨2, 1723261468685⟩, 1),
    (⟨2, 1809314218082⟩, 0),
    (⟨2, 1835791987127⟩, 0),
    (⟨2, 2087330793055⟩, 0),
    (⟨2, 2096156716070⟩, 1),
    (⟨2, 2132563648507⟩, 1),
    (⟨2, 2188828907728⟩, 0),
    (⟨2, 2259436291850⟩, -1),
    (⟨2, 2291430262778⟩, 1),
    (⟨2, 2314598310692⟩, 1),
    (⟨2, 2347695521999⟩, 0),
    (⟨2, 2444780675164⟩, 1),
    (⟨3, 211822152361⟩, 0),
    (⟨3, 403785977939⟩, 0),
    (⟨3, 423644304722⟩, 0),
    (⟨3, 529555380905⟩, -2),
    (⟨3, 542794265425⟩, 0),
    (⟨3, 741377533265⟩, -2),
    (⟨3, 765373011461⟩, 0),
    (⟨3, 847288609444⟩, 0),
    (⟨3, 867146936227⟩, -1),
    (⟨3, 1085588530850⟩, -1),
    (⟨3, 1138544068940⟩, 0),
    (⟨3, 1224596818336⟩, 0),
    (⟨3, 1356985663562⟩, 0),
    (⟨3, 1572117537053⟩, 0),
    (⟨3, 1590321003271⟩, 0),
    (⟨3, 1694577218888⟩, -1),
    (⟨3, 1714435545670⟩, 0),
    (⟨3, 1734293872454⟩, -1),
    (⟨3, 1853443833157⟩, 0),
    (⟨3, 1989142399513⟩, 0),
    (⟨3, 2038788216473⟩, -1),
    (⟨3, 2042097937603⟩, 0),
    (⟨3, 2071885427779⟩, 0),
    (⟨3, 2091743754563⟩, 0),
    (⟨3, 2237371484311⟩, 0),
    (⟨3, 2369760329536⟩, 0),
    (⟨3, 2403684971125⟩, 0),
    (⟨3, 2416096425365⟩, 0),
    (⟨3, 2449193636672⟩, -1),
    (⟨3, 2475671405717⟩, 0),
    (⟨3, 2568343597375⟩, -1),
    (⟨3, 2584892203028⟩, 0),
    (⟨3, 2753687980691⟩, -1),
    (⟨3, 3130996189583⟩, -1),
    (⟨3, 3180642006542⟩, 0),
    (⟨3, 3198845472761⟩, 0),
    (⟨3, 3250973580568⟩, 0),
    (⟨3, 3428871091340⟩, 0),
    (⟨3, 3468587744908⟩, -1),
    (⟨3, 3521543282999⟩, -1),
    (⟨3, 3548021052043⟩, 0),
    (⟨3, 3706887666314⟩, 0),
    (⟨3, 3854170256627⟩, 0),
    (⟨3, 3895541770760⟩, 0),
    (⟨3, 3978284799026⟩, -1),
    (⟨3, 4077576432946⟩, -1),
    (⟨3, 4084195875206⟩, 0),
    (⟨3, 4143770855558⟩, -1),
    (⟨3, 4183487509126⟩, -1),
    (⟨3, 4246372210607⟩, 0),
    (⟨3, 4474742968622⟩, -1),
    (⟨3, 4633609582892⟩, 0),
    (⟨3, 4739520659072⟩, 0),
    (⟨3, 4807369942250⟩, 0),
    (⟨3, 4832192850730⟩, -1),
    (⟨3, 4858670619775⟩, 0),
    (⟨3, 4871909504303⟩, -3),
    (⟨3, 4931484484649⟩, 0),
    (⟨3, 4967891417087⟩, 0),
    (⟨3, 5020846955176⟩, 0),
    (⟨3, 5096970541181⟩, 0),
    (⟨3, 5136687194750⟩, -2),
    (⟨3, 5189642732839⟩, 0),
    (⟨3, 5378296837285⟩, 0),
    (⟨3, 5454420423290⟩, 0),
    (⟨3, 5548747475513⟩, 0),
    (⟨3, 5573570383993⟩, 0),
    (⟨3, 5586809268515⟩, 0),
    (⟨3, 5935984847797⟩, 0),
    (⟨3, 5983975804193⟩, -1),
    (⟨3, 6089886880373⟩, -1),
    (⟨3, 6242134052381⟩, 0),
    (⟨3, 6248753494645⟩, -2),
    (⟨3, 6278540984818⟩, 0),
    (⟨3, 6361284013084⟩, 0),
    (⟨3, 6501947161136⟩, 0),
    (⟨3, 6526770069617⟩, -1),
    (⟨3, 6606203376751⟩, 0),
    (⟨3, 6804786644590⟩, 0),
    (⟨3, 6857742182680⟩, 0),
    (⟨3, 6933865768684⟩, 0),
    (⟨3, 6937175489816⟩, -1),
    (⟨3, 6957033816599⟩, 0),
    (⟨3, 7076183777302⟩, 0),
    (⟨3, 7096042104086⟩, -1),
    (⟨3, 7201953180269⟩, -2),
    (⟨3, 7249944136661⟩, 0),
    (⟨3, 7284696208532⟩, 0),
    (⟨3, 7413775332628⟩, -1),
    (⟨3, 7479969755240⟩, 0)
  ]

/-- Partial κ-dist function. Unvisited vertices return `none`. -/
def kappa_m1_Q3_dist (v : InvVertex) : Option Int :=
  (kappa_m1_Q3_tbl.find? (·.1 = v)).map (·.2)

/-! ### Bool decision procedures -/

def kappa_m1_Q3_start_check : Bool :=
  decide (kappa_m1_Q3_dist (InvStart 1) = some (0 : Int))

def kappa_m1_Q3_no_goal_check : Bool :=
  kappa_m1_Q3_tbl.all (fun ⟨v, d⟩ =>
    !(decide (v.c % (3 ^ (24 + v.j)) = 1 % (3 ^ (24 + v.j))))
    || !(decide (d < (1 : Int))))

def kappa_m1_Q3_closed_check : Bool :=
  kappa_m1_Q3_tbl.all (fun ⟨s, d⟩ =>
    let credit_s : Int := (3 : Int) - (s.j : Int)
    !(decide (d - credit_s < (1 : Int)))
    || (outgoingEdges 24 3 s).all (fun e =>
      let v := e.1
      let w := e.2
      let nd := d + toKappa s v w
      let credit_v : Int := (3 : Int) - (v.j : Int)
      !(decide (v.j ≤ 3))
      || !(decide (nd - credit_v < (1 : Int)))
      || match kappa_m1_Q3_dist v with
         | some d' => decide (d' ≤ nd)
         | none    => false))

theorem kappa_m1_Q3_start_holds : kappa_m1_Q3_start_check = true := by native_decide
theorem kappa_m1_Q3_no_goal_holds : kappa_m1_Q3_no_goal_check = true := by native_decide
theorem kappa_m1_Q3_closed_holds : kappa_m1_Q3_closed_check = true := by native_decide

/-! ### Bool → Prop soundness -/

lemma kappa_m1_Q3_dist_some_mem {v : InvVertex} {d : Int}
    (h : kappa_m1_Q3_dist v = some d) : (v, d) ∈ kappa_m1_Q3_tbl := by
  unfold kappa_m1_Q3_dist at h
  rcases h_eq : kappa_m1_Q3_tbl.find? (·.1 = v) with _ | ⟨v', d'⟩
  · rw [h_eq] at h; simp at h
  · rw [h_eq] at h
    simp at h
    have h_pred := List.find?_some h_eq
    simp at h_pred
    subst h_pred
    subst h
    exact List.mem_of_find?_eq_some h_eq

theorem kappa_m1_Q3_start_sound : kappa_m1_Q3_dist (InvStart 1) = some 0 :=
  of_decide_eq_true kappa_m1_Q3_start_holds

theorem kappa_m1_Q3_no_goal_sound :
    ∀ v d, kappa_m1_Q3_dist v = some d → InvVertex.IsGoal v 24 → ¬ d < (1 : Int) := by
  intro v d h_dist h_goal h_lt
  have h_mem := kappa_m1_Q3_dist_some_mem h_dist
  have h := kappa_m1_Q3_no_goal_holds
  unfold kappa_m1_Q3_no_goal_check at h
  rw [List.all_eq_true] at h
  have h_p := h (v, d) h_mem
  unfold InvVertex.IsGoal at h_goal
  simp only [Bool.or_eq_true, Bool.not_eq_true', decide_eq_false_iff_not] at h_p
  exact h_p.elim (fun hg => hg h_goal) (fun hd => hd h_lt)

theorem kappa_m1_Q3_closed_sound :
    ∀ v d, kappa_m1_Q3_dist v = some d → relevant 3 (1 : Int) v d →
      ∀ e ∈ outgoingEdges 24 3 v, e.1.j ≤ 3 →
        relevant 3 (1 : Int) e.1 (d + toKappa v e.1 e.2) →
        ∃ d', kappa_m1_Q3_dist e.1 = some d' ∧ d' ≤ d + toKappa v e.1 e.2 := by
  intro v d h_dist h_v_rel e h_e_in h_e_j_le h_e_rel
  have h_v_mem := kappa_m1_Q3_dist_some_mem h_dist
  have h := kappa_m1_Q3_closed_holds
  unfold kappa_m1_Q3_closed_check at h
  rw [List.all_eq_true] at h
  have h_p_v := h (v, d) h_v_mem
  simp only [Bool.or_eq_true, Bool.not_eq_true', decide_eq_false_iff_not] at h_p_v
  rcases h_p_v with h_v_not_rel | h_inner
  · exfalso
    apply h_v_not_rel
    have := h_v_rel
    unfold relevant credit at this
    exact this
  rw [List.all_eq_true] at h_inner
  have h_e_p := h_inner e h_e_in
  simp only [Bool.or_eq_true, Bool.not_eq_true', decide_eq_false_iff_not] at h_e_p
  rcases h_e_p with (h_e_j_neg | h_e_not_rel) | h_match
  · exact (h_e_j_neg h_e_j_le).elim
  · have := h_e_rel
    unfold relevant credit at this
    exact (h_e_not_rel this).elim
  rcases h_dist_e : kappa_m1_Q3_dist e.1 with _ | d'
  · exfalso
    rw [h_dist_e] at h_match
    simp at h_match
  · rw [h_dist_e] at h_match
    refine ⟨d', rfl, ?_⟩
    simpa using h_match

/-! ### Terminal κ barrier -/

theorem kappa_m1_Q3_barrier_internal (u : Word)
    (h_q : (evalWord u).q ≤ 3)
    (h_cyl : (evalWord u).n % (3 ^ 24) = aS202 % (3 ^ 24)) :
    (1 : Int) ≤ defect (evalWord u) :=
  S216_barrier_for_words_via_kappa kappa_m1_Q3_dist
    kappa_m1_Q3_start_sound kappa_m1_Q3_no_goal_sound kappa_m1_Q3_closed_sound u h_q h_cyl

end CollatzLean4.Admissible.Certificates

namespace Cert_m1_Q3_kappa

open CollatzLean4.Admissible
open CollatzLean4.Admissible.Certificates

/-- **`barrier_m1_Q3_kappa : S216BarrierForWords 1 3 1`** — the S202
cylinder accessibility barrier `𝒞^←_{S202}(1, 3) ≥ 1` proved through the
κ-precise (one_edges − τ=1 zero_edges ≥ m) route, end-to-end via the
non-circular bounded chain. -/
theorem barrier_m1_Q3_kappa : S216BarrierForWords 1 3 1 := by
  intro u h_q h_cyl
  exact kappa_m1_Q3_barrier_internal u h_q h_cyl

end Cert_m1_Q3_kappa
